# Generated by Django 5.0 on 2024-08-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciepe',
            old_name='Reciepe_desc',
            new_name='Reciepe_description',
        ),
    ]
